### PR TITLE
Adding macedonian translations.

### LINKED ISSUE #140: Macedonian Translations
**Is your feature request related to a problem? Please describe.**

I would like to translate cstate into Macedonian.

**Describe the solution you'd like**

A Pull Request from me with a new locale(mk) for the Macedonian Language.

**Describe alternatives you've considered**

I can translate to a few other languages for alternatives :smile: 

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by krisfremen**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

Adding Macedonian Translations.

**Test plan**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**Closing issues**

Closes #140

### CODE REVIEW

**Comment by mistermantas** [comment]
This may be a dumb question, but how different is Russian and Macedonian? The reason I ask is cause they both seem to use Cyrillic and I don't _think_ there's a Russian translation for cState but it would be very useful and I think you said (this is a vague memory from when I was reading the GitHub email) that you know other languages?

Anyhow, I need you to translate just two or three more strings. Add this to the bottom of the .yml:

```yml
##
## v4.4
##

- id: in
  translation: in
- id: weeksAgo
  translation: " w"
- id: yearAgo
  translation: " year"
```

At the top of file, you should also change the comment because this is not an English file and it's not offical, so:

```yml
# Macedonian language file for cState
# Version 4.4
```

Lastly, add the language option to Netlify CMS like in this example PR:

https://github.com/cstate/cstate/pull/137/files

**All guidelines, cause I might have missed something** - https://github.com/cstate/cstate/wiki/Translations#add-your-translations

I will merge to DEV, by the way, not master, but honestly it takes some time and effort to translate, so thank you for doing it nonetheless and happy hacktoberfest! Hope you get your reward :)

**Comment by krisfremen** [comment]
@mistermantas sure, I'll do it in Russian as well.

I'll get to these changes very soon.

Chees

**Comment by krisfremen** [comment]
@mistermantas rebased on top of dev, changed the base branch to dev.

Hopefully good to go.

**Comment by mistermantas** [comment]
> @mistermantas sure, I'll do it in Russian as well.

Waiting for your next PR, thank you!

**Pull request merged**
