### PR TITLE
Add links to RSS feeds

### LINKED ISSUE #32: Make RSS feed discoverable
**Is your feature request related to a problem? Please describe.**

I subscribe to the status page of services that I use or run myself via Atom (or RSS) feeds. Hugo generates an RSS feed for its categories, but if the feed is not made discoverable then readers will not know that it exists and can't use it.

**Describe the solution you'd like**

Add a link to the header that points to any alternative representations of the document (such as RSS):

    <link rel="alternate" type="application/rss+xml" href="http://localhost:1313/index.xml" title="My status" />

**Describe alternatives you've considered**

This is the standard way to make alternative representations of the document discoverable, there is no alternative solution.

**Patch**

In accordance with the PR template I did not make a pull request yet, but you can see the entirety of the work required on this page: https://gohugo.io/templates/rss/
A patch which can be used if desired is here: 33876f816a803b7fca26de1cd85265aa604838bb 

https://github.com/SamWhited/cstate/blob/33876f816a803b7fca26de1cd85265aa604838bb/layouts/partials/meta.html#L12-L14

### PR DESCRIPTION
**Pull request by SamWhited**
Fixes #32 

I'm running this on my own status pages, so it is well tested. It is the recommended way to do this according to Hugo as well: https://gohugo.io/templates/rss/

### CODE REVIEW

**Comment by mistermantas** [comment]
Got a link to your status page?

**Comment by SamWhited** [comment]
This one is using it: https://status.soquee.net/

**Comment by mistermantas** [comment]
Lovely looking status page. Not sure why the current ongoing issue is marked with `info`, since that's not a proper status, but apart from that, LGTM.

I recently released a patch, so I'll keep this for v3. Thanks for contributing! ♥️

**Comment by SamWhited** [comment]
> Lovely looking status page. Not sure why the current ongoing issue is marked with info, since that's not a proper status, but apart from that, LGTM.

Oops, thanks; I suppose I must have meant "info" there.

**Pull request merged**
