### PR TITLE
Added "Šebestíček" as an external example site

### PR DESCRIPTION
**Pull request by SebestikCZ**
Added Šebestíček as an external example site :D

### CODE REVIEW

**Comment by mistermantas** [comment]
Hi,

Sorry, but I have to deny this PR because the .tk TLD is used for free domains and therefore often scams.

I do not doubt that your site is legitimate but I could not even visit it (why is there a firewall on a status page anyway?)

Have a nice weekend :)

**Comment by SebestikCZ** [comment]
It is a legitimate website, but I understand you, the firewall is here, because through my website somebody transfered over a gigabyte per month for which I wasn't prepared, and my website is not popular, to get those exceedements.

**Comment by SebestikCZ** [comment]
I can prove it, if you want. I have a free TLD domain, because I don't have enough, entirely don't have any, money to spent on payed domains.

**Comment by SebestikCZ** [comment]
Or an another solution, we can choose a date and time when I turn off additional protection (firewall).

**Pull request closed without merging**
