### PR TITLE
Add Portuguese

### LINKED ISSUE #68: Add Portuguese Language
**Describe the solution you'd like**
A translation for the Portuguese language.

### PR DESCRIPTION
**Pull request by dmcclccam**
This PR adds Portuguese as a language on the platform.

---

Closes #68

### CODE REVIEW

**Comment by mistermantas** [comment]
Have you tried running a site with this language? If possible, send a link. If not, that's fine, I'll have to test it myself a bit later

**Comment by dmcclccam** [comment]
Hey there,

I built it at https://status.unbanked.com.br to provide you with a hosted link.

image

---

image

**Comment by mistermantas** [comment]
side note: main .summary box has an invalid hex code `#8000`

merging!

**Comment by mistermantas** [comment]
you know i’m kinda stupid, this was supposed to go in cstate-dev but i didn’t see so i reverted it but i realized that made a bigger mess

**Comment by dmcclccam** [comment]
Should I make another PR again, to the `dev` branch?

**Comment by mistermantas** [comment]
@dmcclccam Yeah, that’d probably be a good idea

**Pull request merged**
