### PR TITLE
Add enableCustomHTML as hidden field on admin panel to avoid feature-…

### LINKED ISSUE #109: Saving config from admin panel erases `enableCustomHTML` field
**Describe the bug**
When saving via the admin panel, the `enableCustomHTML` field is erased.

**Reproduction steps**
1. Add `enableCustomHTML` to `config.yml`; commit to master
2. Make any change to the `config.yml` from `/admin`
3. Check PR to see that `enableCustomHTML` has been erased

**Expected behavior**
1. The setting isn't erased.

### PR DESCRIPTION
**Pull request by bushong1**
…flag being removed on admin panel save

**Closing issues**

closes #109

### CODE REVIEW

**Comment by mistermantas** [comment]
What I'm wondering is why you would want to keep it hidden? Might as well show it since it's a documented option in the settings.

**Comment by bushong1** [comment]
I figured since there's no way to create/edit/destroy the `layouts/partials/custom/` from the admin panel, you probably wouldn't be turning it on and off from there.  Up to you either way.

**Comment by mistermantas** [comment]
custom partials are empty by default, though. I'm not really sure what this accomplishes.

**Comment by bushong1** [comment]
The way I figure it would work would be like this:

**Person *not* using custom partials**:  Doesn't need to see the setting in the admin panel, since they aren't using it
**Person *already* using custom partials**: Doesn't need to see the setting in the admin panel, since they likely won't be regularly turning it on and off
**Person *looking to start* using custom partials**: Will need to create and populate `layouts/partials/custom/<something>.html`, so they would need to make repository changes outside the admin panel, and would just update the parameter to `true` while adding the html files.

**Comment by mistermantas** [comment]
I honestly don't remember _why_ I added the option `.Site.Params.enableCustomHTML` when the files are quite literally empty by default.

If you don't use them, you don't use them. No effort. Nothing extra should show up.

Disabling HTML doesn't do anything really, should it?

If you want to edit something, you can just go in to the code and do it, the option is kinda useless, isn't it?

...Anyway I'll merge this. Thank you for the report.

**Pull request merged**
