### PR TITLE
Added german translation

### PR DESCRIPTION
**Pull request by gruselhaus**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by mistermantas** [comment]
Thank you! I will test this ASAP and merge it in the next release. 🎉

**Comment by mistermantas** [comment]
I should let you know I found an issue (it’s fixed now tho).

```
- id: notFoundText
  translation: #
```

Fields can’t be empty. They should be completely commented out otherwise like this:

```
#- id: notFoundText
#  translation: 
```

Was the text not translatable?

**Comment by gruselhaus** [comment]
@mistermantas Oh, I missed that one. I will open a new pr with the fix shortly.

**Comment by mistermantas** [comment]
Great! Set the branch to v4.p

**Pull request merged**
