### PR TITLE
Added turkish translation

### PR DESCRIPTION
**Pull request by 0xbkt**
There seems to be a German translation PR and if either is merged, it will cause a conflict and I guess the repo owner should cherry pick or so to resolve conflicts.

### CODE REVIEW

**Comment by mistermantas** [comment]
Hi. Repo owner here.

Why so? And thanks for contributing!

**Comment by 0xbkt** [comment]
@mistermantas I'm not even sure but I guess because two PRs alter the same lines in `config.yml`.

**Comment by mistermantas** [comment]
I mean, I’d assume Git would be smart enough to recognize that.

If not, I can manually edit the PR and make it work.

**Comment by mistermantas** [comment]
While compiling I found an issue.

```toml
- id: resolvedAfter
  translation: Çözümlendi: # + 19 min
```

There can’t be two colons (`:`).

This doesn’t make sense to cState (or Hugo, or any TOML parser): `lorem: ipsum:`

I’ve removed the second colon so that the translation doesn’t prevent people from using cState (bad translations, which aren’t even being used, can prevent someone from building a site).

**Comment by 0xbkt** [comment]
@mistermantas If ASCII colon (`:`, hex: 0x3a) is a problem, maybe we can put a similar char instead like Modifier letter colon (`꞉`, hex: 0xa789) or Armenian full stop (`։`, hex: 0x589)

**Comment by mistermantas** [comment]
> Quoting

Hmm?

Anyway, those other characters might work, but they seem like hacks to me, no?

**Comment by 0xbkt** [comment]
@mistermantas Yeah, they are. But I guess you better double quote the value to get the ASCII colon back.

**Comment by mistermantas** [comment]
Can you send a reference? I don’t recall how to escape the colon

**Comment by 0xbkt** [comment]
@mistermantas 

```yaml
- id: resolvedAfter
  translation: "Çözümlendi:"
```

This way. Just quoting the entire text.

**Comment by mistermantas** [comment]
Oh. I tried this. It didn’t work.

**Comment by mistermantas** [comment]
Nevermind, it works

**Pull request merged**
