### PR TITLE
Add RSS link to footer

### LINKED ISSUE #35: Add RSS feed link to footer
index.rss

### PR DESCRIPTION
**Pull request by SamWhited**
Fixes #35

Let me know if you'd prefer to use an RSS icon or something similar.

### CODE REVIEW

**Comment by SamWhited** [comment]
I should also mention that this will always give a link to the feed for the current page; so if you are on a component list page the feed will be just for that component. I'm not sure if this is desirable or if you'd prefer to always link the full feed here?

**Comment by mistermantas** [comment]
@SamWhited Both? Like `RSS: all - only this feed` or something similar

**Comment by SamWhited** [comment]
Done:

screenshot

**Comment by mistermantas** [comment]
Splendid. Thanks once again!

**Comment by SamWhited** [comment]
Already fixed, see: https://github.com/cstate/cstate/issues/35#issuecomment-429089788

**Pull request closed without merging**
